name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: NPM Install
        run: npm ci

      - name: ESLint
        uses: xt0rted/eslint-action@d9bd6dd0a116fc40c6d7a478c856eefd63bd4d07
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
