name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: NPM Install
        # to install eslint
        run: npm ci

      - name: ESLint
        run: npm run lint
